apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service
  namespace: jd-mm
data:
  application.yml: |-
    spring:
      cloud:
        kubernetes:
          discovery:
            enabled: true
          loadbalancer:
            enabled: true
        discovery:
          enabled: true
    ribbon:
      eureka:
        enabled: false
    eureka:
      client:
        enabled: false
        fetch-registry: false
    ---
    spring:
      cloud:
        gateway:
          routes:
            - id: moneymaker-account-service
              uri: lb://moneymaker-account-service
              predicates:
                - Path=/v1/accounts/**
            - id: moneymaker-transaction-service
              uri: lb://moneymaker-transaction-service
              predicates:
                - Path=/v1/transactions/**
            - id: moneymaker-budget-service
              uri: lb://moneymaker-budget-service
              predicates:
                - Path=/v1/budgets/**
    ---
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
        restart:
          enabled: true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: moneymaker-transaction-service
  namespace: jd-mm
data:
  application.yml: |-
    spring:
      cloud:
        kubernetes:
          discovery:
            enabled: true
          loadbalancer:
            enabled: true
        discovery:
          enabled: true
    ribbon:
      eureka:
        enabled: false
    eureka:
      client:
        enabled: false
        fetch-registry: false
    ---
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
        restart:
          enabled: true
    ---
    spring:
      r2dbc:
        url: r2dbc:pool:mysql://moneymaker-mysql-service:3306/mm_transaction_dev
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
      flyway:
        url: jdbc:mysql://moneymaker-mysql-service:3306/mm_transaction_dev
        user: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        baseline-on-migrate: true
    ---
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: https://keycloak.factotumsoftware.com/auth/realms/jd-mm
          client:
            registration:
              oaka-transaction-service:
                provider: keycloak
                client-id: oaka-transaction-service
                client-secret: ${OAUTH2_CLIENT_SECRET}
                authorization-grant-type: client_credentials
            provider:
              keycloak:
                issuer-uri: https://keycloak.factotumsoftware.com/auth/realms/jd-mm
    ---
    spring:
      rabbitmq:
        host: moneymaker-rabbitmq-service
        port: 5673
        username: ${RABBIT_USERNAME}
        password: ${RABBIT_PASSWORD}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: moneymaker-account-service
  namespace: jd-mm
data:
  application.yml: |-
    spring:
      cloud:
        kubernetes:
          discovery:
            enabled: true
          loadbalancer:
            enabled: true
        discovery:
          enabled: true
    ribbon:
      eureka:
        enabled: false
    eureka:
      client:
        enabled: false
        fetch-registry: false
    ---
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
        restart:
          enabled: true
    ---
    spring:
      r2dbc:
        url: r2dbc:pool:mysql://moneymaker-mysql-service:3306/mm_account_dev
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
      flyway:
        url: jdbc:mysql://moneymaker-mysql-service:3306/mm_account_dev
        user: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        baseline-on-migrate: true
    ---
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: https://keycloak.factotumsoftware.com/auth/realms/jd-mm
          client:
            registration:
              setzer-account-service:
                provider: keycloak
                client-id: setzer-account-service
                client-secret: ${OAUTH2_CLIENT_SECRET}
                authorization-grant-type: client_credentials
            provider:
              keycloak:
                issuer-uri: https://keycloak.factotumsoftware.com/auth/realms/jd-mm
    ---
    spring:
      rabbitmq:
        host: moneymaker-rabbitmq-service
        port: 5673
        username: ${RABBIT_USERNAME}
        password: ${RABBIT_PASSWORD}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: moneymaker-budget-service
  namespace: jd-mm
data:
  application.yml: |-
    spring:
      cloud:
        kubernetes:
          discovery:
            enabled: true
          loadbalancer:
            enabled: true
        discovery:
          enabled: true
    ribbon:
      eureka:
        enabled: false
    eureka:
      client:
        enabled: false
        fetch-registry: false
    ---
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
        restart:
          enabled: true
    ---
    spring:
      datasource:
        url: jdbc:mysql://moneymaker-mysql-service:3306/mm_budget_dev
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        flyway:
          baseline-on-migrate: true
    ---
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: https://keycloak.factotumsoftware.com/auth/realms/jd-mm
          client:
            registration:
              rin-budget-service:
                provider: keycloak
                client-id: rin-budget-service
                client-secret: ${OAUTH2_CLIENT_SECRET}
                authorization-grant-type: client_credentials
            provider:
              keycloak:
                issuer-uri: https://keycloak.factotumsoftware.com/auth/realms/jd-mm
    ---
    spring:
      rabbitmq:
        host: moneymaker-rabbitmq-service
        port: 5673
        username: ${RABBIT_USERNAME}
        password: ${RABBIT_PASSWORD}
