apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mm-dev-certificate
  namespace: jd-mm
spec:
  dnsNames:
    - moneymaker.jaydamon.com
  secretName: mm-issuer-key
  issuerRef:
    name: factotum-issuer
    kind: ClusterIssuer
