apiVersion: v1
kind: ConfigMap
metadata:
  name: moneymaker-config
  namespace: jd-mm
data:
  profile-active: prod
  configuration.json: |
    {
      "resourceServer":"https://moneymaker.jaydamon.com/api",
      "keycloak": {
        "url": "https://keycloak.factotumsoftware.com/auth",
        "realm": "jd-mm",
        "clientId": "cid-client"
      }
    }
