apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: moneymaker-configmap-reader
  namespace: jd-mm
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: moneymaker-configmap-reader
  namespace: jd-mm
subjects:
  - kind: ServiceAccount
    name: default
    namespace: jd-mm
roleRef:
  kind: Role
  name: moneymaker-configmap-reader
  apiGroup: rbac.authorization.k8s.io
