apiVersion: v1
kind: ConfigMap
metadata:
  name: media-library-storage-service
  namespace: media-jd
data:
  application.yml: |-
      datasource:
        url: jdbc:mysql://mysql-service:3306/media_library_storage_service
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}